展开文件树
工作
工作
DecYanYuScript
权限
工作流

在

在:
  release:
面包屑

师父步骤:
  build:

DecYanYuScript
取消更改:
工作流
提交更改...

与:
师父
取消更改
编辑
预演:
在
缩进模式预演在展开文件树面包屑
空步骤面包屑展开文件树
空步骤面包屑展开文件树

制表符师父工作编辑工作流文件在 deyanyouscrimpt
缩进模式预演在展开文件树面包屑

选择或粘贴它们，我在你身边吗制表符师父工作空步骤面包屑展开文件树编辑工作流文件在 deyanyouscrimpt
使用降价让你怎么看与权限缩进尺寸取消更改工作空步骤面包屑展开文件树

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
